[package]
name = "wasm-prime"
version = "0.1.0"
authors = ["Theodore Ehrenborg <theodore.ehrenborg@gmail.com>"]
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
web-sys = "0.3.77"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-iter = "0.1.45"
num-traits = "0.2"
gloo-timers = "0.3.0"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
