[package]
name = "wasm-prime"
version = "0.1.0"
authors = ["Theodore Ehrenborg <theodore.ehrenborg@gmail.com>"]
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
web-sys = "0.3.77"
num-bigint = "0.4.6"
num-iter = "0.1.45"
gloo-timers = "0.3.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
